version: '0'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 5000:5000
    volumes:
      - /Users/jinzekun/Documents/github/vite-quickstart-ts/nginx.conf:/etc/nginx/nginx.conf
      - /Users/jinzekun/Documents/github/vite-quickstart-ts/dist:/data/vite-quickstart-ts
